### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by KorkyraBoyCRO** [sandeepmistry/arduino-BLEPeripheral#17]
Hi...i have problem with verifying example codes like ancs etc
I placed the BLEPeripheral Library normally in my documents arduino library file and opened it in arduino IDE....after hitting verify button i got this error:

     processing.app.debug.RunnerException: Couldn't create: /var/folders/cw/kgqbm6bn5v1b1h_lfcj6kbc80000gn/T/build6693720258264982059.tmp/SPI
	at processing.app.debug.Compiler.createFolder(Compiler.java:705)
	at processing.app.debug.Compiler.compile(Compiler.java:149)
	at processing.app.Sketch.build(Sketch.java:1585)
	at processing.app.Sketch.build(Sketch.java:1562)
	at processing.app.Editor$DefaultRunHandler.run(Editor.java:1899)
	at java.lang.Thread.run(Thread.java:695)
        Users/myname/Documents/Arduino/libraries/BLEPeripheral/BLEProgmemConstantCharacteristic.cpp: In constructor 'BLEProgmemConstantCharacteristic::BLEProgmemConstantCharacteristic(const char*, const char*)':
      /Users/myname/Documents/Arduino/libraries/BLEPeripheral/BLEProgmemConstantCharacteristic.cpp:10: error: 'strlen_PF' was not declared in this scope  
     /Users/myname/Documents/Arduino/libraries/BLEPeripheral/BLEProgmemConstantCharacteristic.cpp:10: error: 'strlen_PF' was not declared in this scope

**Comment by sandeepmistry** [comment]
@KorkyraBoyCRO more details please:

 * Which board are you using?
 * Which Arduino IDE version are you building with?
 * Which version of the library are you using (Git commit)?

**Comment by KorkyraBoyCRO** [comment]
I am on the Uno R3 but i havent uploaded the code onto chip, i just tried to verify it ( i always first check it that way and if everything is ok i upload the code). Should i try to upload it ? As far as i know i have the latest IDE cause i had to reinstal arduino last month ( btw i am on the mac ) and for the library i also think it is last versio. I found it yesterday so i suppose it is the last

**Comment by KorkyraBoyCRO** [comment]
I hope that ee can fix this cause i an really hoping ti get this run on arduino it look super cool and easy to work with code all in all it is awesome library

**Comment by sandeepmistry** [comment]
@KorkyraBoyCRO a36a03a should fix this.

It was working with the new Arduino 1.6.x IDE, but not with the older 1.0.x IDE. In the future please provide exact version numbers, instead of using terms like the "latest".
